[[redirects]]
  from = "/empleos/*"
  to = "/.netlify/functions/proxy?path=/empleos/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/tipoprocesoseleccion/*"
  to = "/.netlify/functions/proxy?path=/tipoprocesoseleccion/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/convocatorias/*"
  to = "/.netlify/functions/proxy?path=/convocatorias/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/entidades/*"
  to = "/.netlify/functions/proxy?path=/entidades/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/departamento/*"
  to = "/.netlify/functions/proxy?path=/departamento/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/municipio/*"
  to = "/.netlify/functions/proxy?path=/municipio/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/niveles/*"
  to = "/.netlify/functions/proxy?path=/niveles/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/tipodiscapacidad/*"
  to = "/.netlify/functions/proxy?path=/tipodiscapacidad/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
